### ISSUE TITLE
option gridOpacity is not working

### ISSUE THREAD

**Issue by akvaliya** [jkuri/ngx-slimscroll#110]
gridOpacity in options is not working.

I have below default options
  ```
{
            provide: SLIMSCROLL_DEFAULTS,
            useValue: {
                alwaysVisible: false,
                gridOpacity: '0.6', barOpacity: '0.4',
                gridBackground: '#C2C2C2',
                gridWidth: '6',
                gridMargin: '2px 2px',
                barBackground: '#2C3E50',
                barWidth: '6',
                barMargin: '2px 2px'
            }
        }
```

No matter what value i set in `gridOpacity`. It's not working. Can anyone help me resolve this.
I don't want to display grid so i want to set gridOpacity to 0. But none of the value works

**Comment by jkuri** [comment]
please try new version `7.1.0` from `npm`. should work now.

**Comment by akvaliya** [comment]
Yes. Worked with new version. Thanks.
