### ISSUE TITLE
Error with BrowserAnimationsModule/NoopAnimationsModule

### ISSUE THREAD

**Issue by Korigoth** [jkuri/ngx-slimscroll#113]
I get this error in a fresh angular app with ngx-slimscroll 7.1.0

Found the synthetic property @expandCollapse. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

I've added my BrowserAnimationsModule in my AppModule but still getting this error!
Tried with NoopAnimationsModule too and i get the same error.

There is some talk about the problem here:
https://github.com/angular/angular/issues/18751

**Comment by Korigoth** [comment]
it was in my code... 
seriously sorry,

i didnt check the copy paste with the pluggin and there was an [@expandCollapse]="" inside it... without me declaring it in the component!

**Comment by vyapariapp** [comment]
But my problem is not solved and i don't add any other code and i included import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
 but the error is not solving
