### ISSUE TITLE
Compilation error after upgrading to angular 9 (ts version 3.7.5)

### ISSUE THREAD

**Issue by zkozniak** [jkuri/ngx-slimscroll#115]
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 971:68-74
"export 'default' (imported as 'common') was not found in '@angular/common'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 122:34-38
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 374:39-43
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 980:27-31
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 979:38-42
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 978:32-36
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 977:31-35
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 976:26-30
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 975:26-30
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 972:125-129
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 972:48-52
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 1070:16-20
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 971:48-52
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 970:73-77
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 970:53-57
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 970:16-20
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 969:80-84
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 969:60-64
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 969:16-20
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 961:16-20
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 373:33-37
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 594:62-66
"export 'default' (imported as 'core') was not found in '@angular/core'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 457:21-30
"export 'default' (imported as 'operators') was not found in 'rxjs/operators'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 451:26-35
"export 'default' (imported as 'operators') was not found in 'rxjs/operators'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 443:22-31
"export 'default' (imported as 'operators') was not found in 'rxjs/operators'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 439:21-30
"export 'default' (imported as 'operators') was not found in 'rxjs/operators'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 432:26-35
"export 'default' (imported as 'operators') was not found in 'rxjs/operators'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 424:22-31
"export 'default' (imported as 'operators') was not found in 'rxjs/operators'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 419:26-30
"export 'default' (imported as 'rxjs') was not found in 'rxjs'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 481:38-42
"export 'default' (imported as 'rxjs') was not found in 'rxjs'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 421:27-31
"export 'default' (imported as 'rxjs') was not found in 'rxjs'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 460:35-39
"export 'default' (imported as 'rxjs') was not found in 'rxjs'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 417:29-33
"export 'default' (imported as 'rxjs') was not found in 'rxjs'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 415:28-32
"export 'default' (imported as 'rxjs') was not found in 'rxjs'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 413:28-32
"export 'default' (imported as 'rxjs') was not found in 'rxjs'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 411:28-32
"export 'default' (imported as 'rxjs') was not found in 'rxjs'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 384:36-40
"export 'default' (imported as 'rxjs') was not found in 'rxjs'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 382:29-33
"export 'default' (imported as 'rxjs') was not found in 'rxjs'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 380:33-37
"export 'default' (imported as 'rxjs') was not found in 'rxjs'
ERROR in ./node_modules/ngx-slimscroll/fesm5/ngx-slimscroll.js 562:44-48
"export 'default' (imported as 'rxjs') was not found in 'rxjs'

**Comment by kkseven07** [comment]
Any solutions?

**Comment by pvrajesh** [comment]
same issue for me, any update on this?
