### ISSUE TITLE
"Import declaration conflict" after upgrading to Angular 9 (TypeScript 3.7)

### ISSUE THREAD

**Issue by SamuelWr** [jkuri/ngx-slimscroll#116]
After upgrading to Angular 9 I get compile errors from this package.
`node_modules/ngx-slimscroll/dist/app/ngx-slimscroll/classes/slimscroll-options.class.d.ts:1:10 - error TS2440: Import declaration conflicts with local declaration of 'ISlimScrollOptions'.`

It seems that `import { ISlimScrollOptions } from './slimscroll-options.class';` on line 1 conflicts with `export interface ISlimScrollOptions {` on line 3

See: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#local-and-imported-type-declarations-now-conflict

**Comment by ManuelRiegler** [comment]
upvote

**Comment by crystalYY** [comment]
I have the same issue

**Comment by crystalYY** [comment]
anyone can fix it?

**Comment by whoknows** [comment]
Having the same issue, has anyone found a workaround ?

**Comment by rodrigocezarmartins** [comment]
I'm having the same issue too...

**Comment by neneplusdev** [comment]
I am also facing same issue.

**Comment by Dahny** [comment]
Same issue here, have there been any updates about this yet?

**Comment by jkuri** [comment]
PRs welcome

**Comment by jkuri** [comment]
I will check on it later today.

**Comment by jkuri** [comment]
done with https://github.com/jkuri/ngx-slimscroll/commit/b950ffb741e4c0f1283fb1ad91ad00e4db5b7ba4
