### ISSUE TITLE
Property 'merge' is missing in type 'ISlimScrollOptions' but required in type 'SlimScrollOptions'.

### ISSUE THREAD

**Issue by mirzinho** [jkuri/ngx-slimscroll#143]
Getting this error on serve when trying to use [options], if options are provided globaly or not used on element , everything works.

`<div class="scroll-area" slimScroll [options]="slimScrollerOptions">`

 Property 'merge' is missing in type 'ISlimScrollOptions' but required in type 'SlimScrollOptions'.
 
 `public slimScrollerOptions: ISlimScrollOptions;`
 
 `this.slimScrollerOptions = {
      barBackground: '#3E3F42',
      gridBackground: '#EFF1F5',
      barBorderRadius: '10',
      barWidth: '6',
      gridWidth: '4',
      gridMargin: '0 1px',
      alwaysVisible: true,
    };`

Angular CLI: 12.0.4
Node: 12.22.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 12.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.4
@angular-devkit/build-angular   12.0.4
@angular-devkit/core            12.0.4
@angular-devkit/schematics      12.0.4
@angular/cli                    12.0.4
@schematics/angular             12.0.4
rxjs                            6.6.7
typescript                      4.2.4

**Comment by jkuri** [comment]
hi @mirzinho, thanks for reporting this, I need to update demo, this is correct:
```ts
import { SlimScrollOptions } from 'ngx-slimscroll';

this.slimScrollerOptions = new SlimScrollOptions({
  barBackground: '#3E3F42',
  gridBackground: '#EFF1F5',
  barBorderRadius: '10',
  barWidth: '6',
  gridWidth: '4',
  gridMargin: '0 1px',
  alwaysVisible: true
});
```
