### ISSUE TITLE
Prevent parent scrolling when child is scrolled

### ISSUE THREAD

**Issue by mirzinho** [jkuri/ngx-slimscroll#144]
I have a container inside a container that both have slimscroll.

Is there a way to prevent parent scrolling while the mouse is scrolling inside the child.

Some option to prevent event bubbling to parent,

**Comment by jkuri** [comment]
hi @mirzinho I am not sure how to solve this, you should somehow call stopPropagation on that event. did you maybe solve this problem?

**Comment by mirzinho** [comment]
Unfortunately not yet, been trying to get around it, looking at the jQuery SlimScroll from rochal, that thing has a allowPageScroll: boolean; property that disables page / parent scroll, so i am looking to see how that has been solved.

Maybe you should give it a look..

**Comment by jkuri** [comment]
hi @mirzinho, I solved this by adding `lock` and `unlock` events. This is now available since version `12.2.0`.
You can check live demo [here](https://ngx-slimscroll.jankuri.com/). Let me know if it works for you, when you have time to check it out.
