### ISSUE TITLE
ngx-slimscroll@3.5.0  doesn't work

### ISSUE THREAD

**Issue by demo-igor** [jkuri/ngx-slimscroll#75]
It looks like package has wrong structure. I see app folder and packages structure really different between ngx-slimscroll@3.3.0 and ngx-slimscroll@3.5.0

**Comment by abdelrhman92** [comment]
It's not importing correctly for me. Given error
"ERROR in src/app/app.module.ts(15,36): error TS2307: Cannot find module 'ngx-slimscroll'.
src/app/app.module.ts(34,5): error TS2304: Cannot find name 'SlimScroll'."

**Comment by vanessasoutoc** [comment]
i am haved equal erro! Help me

**Comment by FabioGuerreiro** [comment]
@jkuri check the Pull Request

**Comment by markmakes** [comment]
+1

**Comment by jkuri** [comment]
https://github.com/jkuri/ngx-slimscroll/pull/76
