### ISSUE TITLE
Scroll position

### ISSUE THREAD

**Issue by ahmedosama94** [jkuri/ngx-slimscroll#84]
Is it possible to get the current position of the scroll?

**Comment by anil-kk** [comment]
I see that it is not possible to know scroll position using this module, but it is easy to build your own directive to track scroll.

I accomplished this by using my own custom directive (scroll tracker) to know scroll position. 
My use case to know scroll position is to find if scroll is ending, so based on this I implemented infinite scroll behavior, loading more items when scroll is reaching to end.

**Comment by jkuri** [comment]
it would also be possible to emit output event everytime scroll changes, if anyone have time to do it I will accept the PR.

**Comment by anil-kk** [comment]
@jkuri  Yes, of course, I would like to work on this feature if you are willing to adopt it to this module, do you have any specific coding style that is preferred?

**Comment by jkuri** [comment]
@anil-kk great! thanks alot. maybe just check that `npm run lint` passes. I checked and current situation doesn't look very nice :) maybe start with fix linting errors then just follow that styleguide.

**Comment by anil-kk** [comment]
@jkuri I added requested functionality, just let me know your thoughts.

**Comment by ahmedosama94** [comment]
@anil-kk @jkuri  Thanks for the help guys!
