### ISSUE TITLE
Firefox demo, mouse wheel scrolling doesn't work.

### ISSUE THREAD

**Issue by soccerek** [jkuri/ngx-slimscroll#92]
Hi guys,

I have Firefox 59.0.2 and when I want to scroll with mouse wheel, that demo doesn't work:

https://ngx-slimscroll.jankuri.com/

Is it problem only with latest version of Firefox? or with previous too? Do you plan to fix that?

Thanks

**Comment by jkuri** [comment]
hi @soccerek. I think this was introduced with adding scroll sensitivity option [here](https://github.com/jkuri/ngx-slimscroll/blob/master/src/app/ngx-slimscroll/directives/slimscroll.directive.ts#L311-L314). 
It is definitelly in my plan to fix that since its a critical issue. Thanks for report!

**Comment by jkuri** [comment]
https://github.com/jkuri/ngx-slimscroll/commit/95b1991010303410e3d9b304bc778cb95557d2a6
