### ISSUE TITLE
need a property on directive or class on wrapper to show scrollbar is hidden

### ISSUE THREAD

**Issue by scott-ho** [jkuri/ngx-slimscroll#98]
In my case, i need to know whether the scrollbar occurs. But for now there is no way to get it directly. I could only make a settimtout to detect it. That's not nice.

**Comment by jkuri** [comment]
you can simply add event into codebase and make a pull request for that, I'll accept it.

**Comment by e-cloud** [comment]
@jkuri I've make a pr for the issue with an extra feature

**Comment by scott-ho** [comment]
@jkuri the pr above seems good. Could you review it?
